# Generated by Django 4.0.3 on 2022-03-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_alter_jobs_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='number_of_employees',
            field=models.CharField(choices=[('less than 200', 'less than 200'), ('200 to 500', '200 to 500'), ('500 to 1000', '500 to 1000'), ('more than 1000', 'more than 1000')], default='less than 200', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='services',
            field=models.CharField(choices=[('software services', 'software services'), ('training services', 'training services'), ('event planning services', 'event planning services'), ('consulting services', 'consulting services'), ('marketing services', 'marketing services'), ('construction services', 'construction services'), ('legal services', 'legal services'), ('delivery services', 'delivery services'), ('real estate services', 'real estate services'), ('health care services', 'health care services'), ('education', 'education'), ('other', 'other')], default='other', max_length=500),
        ),
    ]
