# Generated by Django 4.0.3 on 2022-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_companyprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='Bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='recruter_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
