# Generated by Django 4.0.3 on 2022-03-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('qualification', models.CharField(choices=[('post graduate', 'post graduate'), ('graduate', 'graduate'), ('under graduate', 'under graduate')], default='graduate', max_length=50)),
                ('experience', models.CharField(choices=[('0-1', 'o-1'), ('2-5', '2-5'), ('5-6', '5-6'), ('6-8', '6-8'), ('8-10', '8-10'), ('more than 10', 'more than 10')], max_length=50)),
                ('skills', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='files')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='Employer.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.jobs')),
            ],
        ),
    ]
