# Generated by Django 4.0.3 on 2022-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0004_alter_applications_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('on hold', 'on hold')], max_length=50),
        ),
    ]
