# Generated by Django 4.0.3 on 2022-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0005_alter_applicant_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('under_processing', 'under_processing')], max_length=50),
        ),
    ]
