# Generated by Django 4.0.3 on 2022-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0007_alter_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status_updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
