# Generated by Django 4.0.3 on 2022-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0009_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('under_processing', 'under_processing')], default='under_processing', max_length=50),
        ),
    ]
